import { z } from "zod";

const envSchema = z.object({
  DATABASE_URL: z.string().min(1),
  SLACK_BOT_TOKEN: z.string().optional(),
  SLACK_APP_TOKEN: z.string().optional(),
  SLACK_SIGNING_SECRET: z.string().optional(),
  CONTENTDESK_APP_URL: z.string().url().optional(),
  PARALLEL_API_KEY: z.string().optional(),
  AI_GATEWAY_API_KEY: z.string().optional(),
  CONTENTDESK_AI_MODEL: z.string().optional(),
  CONTENTDESK_IMAGE_MODEL: z.string().optional(),
  BLOB_READ_WRITE_TOKEN: z.string().optional(),
  GOOGLE_SERVICE_ACCOUNT_JSON: z.string().optional(),
  GA4_PROPERTY_ID: z.string().optional(),
  GSC_SITE_URL: z.string().optional(),
  SHOPIFY_PARTNER_TOKEN: z.string().optional(),
  SHOPIFY_PARTNER_ORG_ID: z.string().optional(),
  SHOPIFY_PARTNER_APP_ID: z.string().optional(),
  SHOPIFY_PARTNER_API_VERSION: z.string().optional(),
  POSTHOG_API_KEY: z.string().optional(),
  POSTHOG_PROJECT_ID: z.string().optional(),
  POSTHOG_HOST: z.string().optional(),
  ANALYTICS_BRAND_SLUG: z.string().optional(),
  ANALYTICS_SLACK_CHANNEL_ID: z.string().optional(),
});

export function getEnv() {
  return envSchema.parse({
    DATABASE_URL: process.env.DATABASE_URL,
    SLACK_BOT_TOKEN: process.env.SLACK_BOT_TOKEN,
    SLACK_APP_TOKEN: process.env.SLACK_APP_TOKEN,
    SLACK_SIGNING_SECRET: process.env.SLACK_SIGNING_SECRET,
    CONTENTDESK_APP_URL: process.env.CONTENTDESK_APP_URL,
    PARALLEL_API_KEY: process.env.PARALLEL_API_KEY,
    AI_GATEWAY_API_KEY: process.env.AI_GATEWAY_API_KEY,
    CONTENTDESK_AI_MODEL: process.env.CONTENTDESK_AI_MODEL,
    CONTENTDESK_IMAGE_MODEL: process.env.CONTENTDESK_IMAGE_MODEL,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    GOOGLE_SERVICE_ACCOUNT_JSON: process.env.GOOGLE_SERVICE_ACCOUNT_JSON,
    GA4_PROPERTY_ID: process.env.GA4_PROPERTY_ID,
    GSC_SITE_URL: process.env.GSC_SITE_URL,
    SHOPIFY_PARTNER_TOKEN: process.env.SHOPIFY_PARTNER_TOKEN,
    SHOPIFY_PARTNER_ORG_ID: process.env.SHOPIFY_PARTNER_ORG_ID,
    SHOPIFY_PARTNER_APP_ID: process.env.SHOPIFY_PARTNER_APP_ID,
    SHOPIFY_PARTNER_API_VERSION: process.env.SHOPIFY_PARTNER_API_VERSION,
    POSTHOG_API_KEY: process.env.POSTHOG_API_KEY,
    POSTHOG_PROJECT_ID: process.env.POSTHOG_PROJECT_ID,
    POSTHOG_HOST: process.env.POSTHOG_HOST,
    ANALYTICS_BRAND_SLUG: process.env.ANALYTICS_BRAND_SLUG,
    ANALYTICS_SLACK_CHANNEL_ID: process.env.ANALYTICS_SLACK_CHANNEL_ID,
  });
}
